ALTER TABLE `ccf`.`pc_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`graveyard_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`mens_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`missionary_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`primary_school_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`womens_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`sto_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`sunday_school_account` ADD COLUMN `date` DATE NOT NULL;
ALTER TABLE `ccf`.`youth_account` ADD COLUMN `date` DATE NOT NULL;